import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

// Fonts are used to define the fonts used in the application
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const linkStyle = "p-5 bg-[#333334] text-blue-500 hover:bg-[#505051]";

// Metadata is used to define the metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The root layout is the top-level component that wraps all pages in the app directory
// Everything outside children is rendered on every route
// Children is route dependent content

// Justify-center aligns items on the main-axis (horizontal in this case)
// Items-center aligns items on the cross-axis (vertical in this case)
export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-[#1f1e1e] flex justify-center items-center h-[5vh] w-full">
          <Link href="/react" className={linkStyle}>React</Link>
          <Link href="/javascript" className={linkStyle}>Javascript</Link>
          <Link href="/node" className={linkStyle}>Node.JS</Link>
        </nav>
        <div className="flex justify-center">
          <div className="flex flex-col items-center bg-[#282828] w-1/2 min-h-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
